### ISSUE TITLE
Please Driver for AZ GO 2 wifi mount, thanks 

### ISSUE THREAD

**Issue by Tommydeep** [ascomghostdrivers/legacydrivers#3]

**Comment by Peter-Simpson** [comment]
Hi Tommy,

This may be what you are looking for: [SynScan ASCOM Driver](https://skywatcher.com/download/software/ascom-driver/) 

If this isn't what you need I suggest asking Sky Watcher support for help: [SkyWatcher Contact Us](https://skywatcher.com/where-to-buy/).

Best wishes, Peter
